CREATE TABLE AMBIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    TIPO CHAR(1) NOT NULL DEFAULT 'N',
    ID_USUARIO INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
);

ALTER TABLE AMBIENTE ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);
ALTER TABLE AMBIENTE ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID);