INSERT INTO APARELHO (DESCRICAO, CONSUMO, FABRICANTE, MODELO, ID_REDE_ELETRICA) VALUES
('Geladeira', 200, 'Geladeiras MAX', 'Duas Portas', 1),
('Ventilador', 80, 'VentoSul', 'Oscilante 40cm', 1),
('Micro-ondas', 1300, 'CozinheBem', 'Digital 30L', 1),
('Televisão', 100, 'SuperVisor', 'Smart LED 50"', 3),
('Computador', 250, 'TechPro', 'Desktop i5 8GB', 3),
('Notebook', 90, 'NoteTop', 'Ultrafino Ryzen 5', 3),
('Máquina de Lavar', 500, 'LavaTudo', '10kg Turbo', 1),
('Impressora', 40, 'PrintMax', 'Laser Mono', 3),
('Forno Elétrico', 1500, 'AssaBem', 'Grill 45L', 1),
('Carregador de Celular', 10, 'EletroPlug', 'USB-C 25W', 3),
('Cafeteira', 1000, 'CaféExpress', 'Automática Inox', 3),
('Liquidificador', 500, 'BateForte', '3 Velocidades', 1),
('Chuveiro Elétrico', 5500, 'BanhoQuente', 'Turbo 220V', 1),
('Aquecedor de Ambiente', 1800, 'ClimaBom', 'Cerâmico 1500W', 2),
('Lâmpada LED', 10, 'LuzClara', '9W E27', 2),
('Smart Speaker', 15, 'VozHouse', 'Assistente Virtual', 1),
('Modem/Router', 25, 'NetLink', 'Wi-Fi Dual Band', 2),
('Xbox Series S', 170, 'Microsoft', '512GB', 1),
('PlayStation 5', 200, 'Sony', 'Digital Edition', 1);