CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR(20) NOT NULL,
    SENHA VARCHAR(100) NOT NULL
);