CREATE TABLE AMBIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    FOTO VARCHAR(255)
);

ALTER TABLE AMBIENTE ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE;
ALTER TABLE AMBIENTE ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID);