CREATE TABLE APARELHO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    TENSAO FLOAT(4,2) NOT NULL,
    ID_REDE_ELETRICA INT NOT NULL
);

ALTER TABLE APARELHO ADD FOREIGN KEY (ID_REDE_ELETRICA) REFERENCES REDE_ELETRICA(ID) ON DELETE CASCADE;