CREATE VIEW VIEW_ENDERECO AS
SELECT
    E.ID AS ID_ENDERECO,
    E.RUA,
    E.NUMERO,
    B.NOME AS BAIRRO,
    C.NOME AS CIDADE,
    ES.SIGLA AS ESTADO_SIGLA,
    ES.NOME AS ESTADO_NOME
FROM ENDERECO E
LEFT JOIN BAIRRO B ON E.ID_BAIRRO = B.ID
LEFT JOIN CIDADE C ON B.ID_CIDADE = C.ID
LEFT JOIN ESTADO ES ON C.ID_ESTADO = ES.ID;