CREATE TABLE GERADOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    POTENCIA FLOAT NOT NULL, 
    TIPO VARCHAR(10),
    FABRICANTE VARCHAR(50),
    MODELO VARCHAR(50),
    ID_AMBIENTE INT NOT NULL
);

ALTER TABLE GERADOR ADD FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID) ON DELETE CASCADE;