CREATE TABLE GERADOR_ENERGIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    POTENCIA FLOAT(6,2) NOT NULL, 
    TIPO VARCHAR(10),
    FABRICANTE VARCHAR(100),
    MODELO VARCHAR(50),
    ID_AMBIENTE INT NOT NULL,
);

ALTER TABLE GERADOR_ENERGIA ADD FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID);