ALTER TABLE GERADOR DROP FOREIGN KEY gerador_ibfk_1;
ALTER TABLE GERADOR DROP COLUMN ID_AMBIENTE;
ALTER TABLE GERADOR DROP COLUMN FABRICANTE;
ALTER TABLE GERADOR DROP COLUMN MODELO;
ALTER TABLE GERADOR MODIFY TIPO VARCHAR(2);
ALTER TABLE GERADOR ADD COLUMN ID_REDE_ELETRICA INT NOT NULL;
ALTER TABLE GERADOR ADD FOREIGN KEY (ID_REDE_ELETRICA) REFERENCES REDE_ELETRICA(ID) ON DELETE CASCADE;

ALTER TABLE GERADOR CHANGE POTENCIA ENERGIA_GERADA FLOAT;
