ALTER TABLE AMBIENTE
ADD COLUMN TOTAL_APARELHOS_AMBIENTE INTEGER DEFAULT 0 AFTER PERCENTUAL_SUSTENTABILIDADE,
ADD COLUMN GASTO_TOTAL_AMBIENTE FLOAT(6,2) DEFAULT 0 AFTER TOTAL_APARELHOS_AMBIENTE,
ADD COLUMN GASTO_ABATIDO_AMBIENTE FLOAT(6,2) DEFAULT 0 AFTER GASTO_TOTAL_AMBIENTE;