DELIMITER $$

CREATE TRIGGER TR_AI_APARELHO
AFTER INSERT ON APARELHO
FOR EACH ROW
BEGIN
    DECLARE ID_REDE_ELETRICA INT;

    SET ID_REDE_ELETRICA = NEW.ID_REDE_ELETRICA;

    UPDATE REDE_ELETRICA
    SET 
        TOTAL_APARELHOS = TOTAL_APARELHOS + 1,
        GASTO_TOTAL = GASTO_TOTAL + NEW.CONSUMO
    WHERE ID = ID_REDE_ELETRICA;
END$$

DELIMITER ;