DELIMITER $$

CREATE TRIGGER TR_AD_APARELHO
AFTER DELETE ON APARELHO
FOR EACH ROW
BEGIN
    DECLARE ID_REDE_ELETRICA INT;

    SET ID_REDE_ELETRICA = OLD.ID_REDE_ELETRICA;

    UPDATE REDE_ELETRICA
    SET 
        TOTAL_APARELHOS = TOTAL_APARELHOS - 1,
        GASTO_TOTAL = GASTO_TOTAL - OLD.CONSUMO
    WHERE ID = ID_REDE_ELETRICA;
END$$

DELIMITER ;