DELIMITER $$

CREATE TRIGGER TR_AU_APARELHO
AFTER UPDATE ON APARELHO
FOR EACH ROW
BEGIN
    DECLARE ID_REDE_ELETRICA INT;

    SET ID_REDE_ELETRICA = NEW.ID_REDE_ELETRICA;

    UPDATE REDE_ELETRICA
    SET GASTO_TOTAL = GASTO_TOTAL - OLD.CONSUMO + NEW.CONSUMO 
    WHERE ID = ID_REDE_ELETRICA;
END$$

DELIMITER ;