DELIMITER $$

CREATE TRIGGER TR_AI_GERADOR
AFTER INSERT ON GERADOR
FOR EACH ROW
BEGIN
    DECLARE ID_REDE_ELETRICA INT;

    SET ID_REDE_ELETRICA = NEW.ID_REDE_ELETRICA;

    UPDATE REDE_ELETRICA
    SET 
        TOTAL_APARELHOS = TOTAL_APARELHOS + 1,
        GASTO_ABATIDO = GASTO_ABATIDO + NEW.ENERGIA_GERADA
    WHERE ID = ID_REDE_ELETRICA;
END$$

DELIMITER ;