DELIMITER $$

CREATE TRIGGER TR_AD_GERADOR
AFTER DELETE ON GERADOR
FOR EACH ROW
BEGIN
    DECLARE ID_REDE_ELETRICA INT;

    SET ID_REDE_ELETRICA = OLD.ID_REDE_ELETRICA;

    UPDATE REDE_ELETRICA
    SET 
        TOTAL_APARELHOS = TOTAL_APARELHOS - 1,
        GASTO_ABATIDO = GASTO_ABATIDO - OLD.ENERGIA_GERADA
    WHERE ID = ID_REDE_ELETRICA;
END$$

DELIMITER ;