DELIMITER $$

CREATE TRIGGER TR_AU_GERADOR
AFTER UPDATE ON GERADOR
FOR EACH ROW
BEGIN
    DECLARE ID_REDE_ELETRICA INT;

    SET ID_REDE_ELETRICA = NEW.ID_REDE_ELETRICA;

    UPDATE REDE_ELETRICA
    SET GASTO_ABATIDO = GASTO_ABATIDO - OLD.ENERGIA_GERADA + NEW.ENERGIA_GERADA
    WHERE ID = ID_REDE_ELETRICA;
END$$

DELIMITER ;