DELIMITER $$

CREATE TRIGGER TR_AI_REDE_ELETRICA
AFTER INSERT ON REDE_ELETRICA
FOR EACH ROW
BEGIN
    DECLARE ID_AMBIENTE INT;

    SET ID_AMBIENTE = NEW.ID_AMBIENTE;

    UPDATE AMBIENTE
    SET 
        TOTAL_APARELHOS_AMBIENTE = TOTAL_APARELHOS_AMBIENTE + NEW.TOTAL_APARELHOS,
        GASTO_TOTAL_AMBIENTE = GASTO_TOTAL_AMBIENTE + NEW.GASTO_TOTAL,
        GASTO_ABATIDO_AMBIENTE = GASTO_ABATIDO_AMBIENTE + NEW.GASTO_ABATIDO
    WHERE ID = ID_AMBIENTE;
END$$

DELIMITER ;