DELIMITER $$

CREATE TRIGGER TR_AU_REDE_ELETRICA
AFTER UPDATE ON REDE_ELETRICA
FOR EACH ROW
BEGIN
    DECLARE ID_AMBIENTE INT;

    SET ID_AMBIENTE = NEW.ID_AMBIENTE;

    UPDATE AMBIENTE
    SET 
        TOTAL_APARELHOS_AMBIENTE = TOTAL_APARELHOS_AMBIENTE - OLD.TOTAL_APARELHOS + NEW.TOTAL_APARELHOS,
        GASTO_TOTAL_AMBIENTE = GASTO_TOTAL_AMBIENTE - OLD.GASTO_TOTAL + NEW.GASTO_TOTAL,
        GASTO_ABATIDO_AMBIENTE = GASTO_ABATIDO_AMBIENTE - OLD.GASTO_ABATIDO + NEW.GASTO_ABATIDO
    WHERE ID = ID_AMBIENTE;
END$$

DELIMITER ;