CREATE OR REPLACE VIEW VIEW_REDE_ELETRICA AS
SELECT 
    R.ID,
    R.GASTO_TOTAL,
    R.GASTO_ABATIDO,
    R.TOTAL_APARELHOS,
    A.ID AS ID_APARELHO,
    A.DESCRICAO AS DESCRICAO_APARELHO,
    A.CONSUMO,
    A.FABRICANTE,
    A.TEMPO_DE_USO,
    A.ENCE,
    A.MODELO,
    CASE 
        WHEN A.ID IS NOT NULL THEN 'A'
        WHEN G.ID IS NOT NULL THEN G.TIPO
        ELSE NULL
    END AS TIPO,
    G.ID AS ID_GERADOR,
    G.DESCRICAO AS DESCRICAO_GERADOR,
    G.POTENCIA
FROM REDE_ELETRICA R
LEFT JOIN APARELHO A
    ON R.ID = A.ID_REDE_ELETRICA
LEFT JOIN GERADOR G
    ON R.ID = G.ID_REDE_ELETRICA;