CREATE OR REPLACE VIEW VIEW_APARELHOS AS
SELECT 
    A.ID_REDE_ELETRICA,
    A.ID AS ID_APARELHO,
    A.DESCRICAO AS DESCRICAO_APARELHO,
    A.CONSUMO,
    A.FABRICANTE,
    A.TEMPO_DE_USO,
    A.ENCE,
    A.MODELO,
    G.ID AS ID_GERADOR,
    G.DESCRICAO AS DESCRICAO_GERADOR,
    G.POTENCIA,
    G.TIPO AS TIPO_GERADOR
FROM APARELHO A
LEFT JOIN GERADOR G
    ON A.ID_REDE_ELETRICA = G.ID_REDE_ELETRICA;