CREATE OR REPLACE VIEW VIEW_REDE_ELETRICA AS
SELECT 
    R.ID,
    R.GASTO_TOTAL,
    R.GASTO_ABATIDO,
    R.TOTAL_APARELHOS,
    A.ID AS ID_APARELHO,
    A.DESCRICAO AS DESCRICAO_APARELHO,
    A.CONSUMO,
    A.FABRICANTE,
    A.TEMPO_DE_USO,
    A.ENCE,
    A.MODELO,
    'A' AS TIPO,
    NULL AS ID_GERADOR,
    NULL AS DESCRICAO_GERADOR,
    NULL AS ENERGIA_GERADA
FROM REDE_ELETRICA R
JOIN APARELHO A ON R.ID = A.ID_REDE_ELETRICA

UNION ALL

SELECT 
    R.ID,
    R.GASTO_TOTAL,
    R.GASTO_ABATIDO,
    R.TOTAL_APARELHOS,
    NULL AS ID_APARELHO,
    NULL AS DESCRICAO_APARELHO,
    NULL AS CONSUMO,
    NULL AS FABRICANTE,
    NULL AS TEMPO_DE_USO,
    NULL AS ENCE,
    NULL AS MODELO,
    G.TIPO AS TIPO,
    G.ID AS ID_GERADOR,
    G.DESCRICAO AS DESCRICAO_GERADOR,
    G.ENERGIA_GERADA
FROM REDE_ELETRICA R
JOIN GERADOR G ON R.ID = G.ID_REDE_ELETRICA;